services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
        DATABASE_FILE_NAME: "/app/database/database.sqlite"
        JWT_SECRET: "supersecret-jwt-key-that-is-at-least-32-characters-long"
        S3_ACCESS_KEY: "minioadmin"
        S3_SECRET_KEY: "minioadmin"
        S3_REGION: "us-east-1"
        # S3_ENDPOINT: "http://localhost:9000" # This will work fine on the web version, but not on Expo Go
        S3_ENDPOINT: "http://192.168.1.11:9000" # If you are testing on Expo Go set the address to match your local network, instead of localhost use `hostname -I` to get your local network address
        BUCKET_NAME: "media"
    volumes:
      - ./backend/database:/app/database
    depends_on:
      - minio
    network_mode: "host"

  frontend:
    build:
      args:
        VITE_API_BASE_URL: "http://localhost:3000"
      context: ./frontend
    ports:
      - "80:80"

  minio:
    image: minio/minio
    network_mode: "host"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server /data
    volumes:
      - minio-data:/data

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 3;
        mc alias set local http://localhost:9000 minioadmin minioadmin;
        mc mb -p local/media || true;
        mc anonymous set download local/media;
      "
    network_mode: "host"
    volumes:
      - minio-config:/root/.mc # optional, to persist mc alias config

volumes:
  minio-data:
  minio-config:
