# Fly.io Backend Configuration
app = "media-platform-backend"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"
  FASTIFY_ADDRESS = "0.0.0.0"
  FASTIFY_PORT = "3000"
  DATABASE_FILE_NAME = "/data/database.sqlite"
  S3_REGION = "auto"
  BUCKET_NAME = "misty-frost-1767"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true

[[mounts]]
  source = "media_platform_data"
  destination = "/data"
  initial_size = "1gb"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[deploy]
  strategy = "immediate"

[metrics]
  enabled = false
