name: Deploy to Fly.io

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      # Parallel testing for better performance
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci --prefer-offline --no-audit

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci --prefer-offline --no-audit

      - name: Test Backend
        working-directory: ./backend
        run: |
          npm run build:ts
          npm test

      - name: Test Frontend
        working-directory: ./frontend
        run: |
          npm run lint
          npm run build

  deploy:
    name: Deploy Applications
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        app:
          - { name: "backend", dir: "./backend", config: "fly.toml" }
          - { name: "frontend", dir: "./frontend", config: "fly.toml" }
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: latest

      - name: Deploy ${{ matrix.app.name }}
        working-directory: ${{ matrix.app.dir }}
        run: |
          flyctl deploy --config ${{ matrix.app.config }} --app media-platform-${{ matrix.app.name }} --remote-only
